spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      '[hiberante.format_sql]': true